git name: gflow
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.101=0
  - cuda-runtime=12.1.0=0
  - filelock=3.13.1=py311h06a4308_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.2=py311h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.107=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - markupsafe=2.1.3=py311h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.1=py311h06a4308_0
  - numpy=1.26.3=py311h08b1b3b_0
  - numpy-base=1.26.3=py311hf175353_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.3.1=py311h06a4308_0
  - python=3.11.7=h955ad1f_0
  - pytorch=2.1.2=py3.11_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py311h5eee18b_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchtriton=2.1.0=py311
  - typing_extensions=4.7.1=py311h06a4308_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - alabaster==0.7.15
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==2.4.1
      - autopep8==2.0.4
      - babel==2.14.0
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - decorator==5.1.1
      - dgl==1.1.3+cu121
      - dglgo==0.0.2
      - docutils==0.20.1
      - einops==0.7.0
      - executing==2.0.1
      - fsspec==2023.12.2
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - idna==3.6
      - imagesize==1.4.1
      - ipdb==0.13.13
      - ipython==8.22.2
      - isort==5.13.2
      - jedi==0.19.1
      - joblib==1.3.2
      - littleutils==0.2.2
      - matplotlib-inline==0.1.6
      - numpydoc==1.6.0
      - ogb==1.3.6
      - omegaconf==2.3.0
      - outdated==0.2.2
      - packaging==23.2
      - pandas==2.1.4
      - parso==0.8.3
      - pexpect==4.9.0
      - pillow==10.2.0
      - prompt-toolkit==3.0.43
      - psutil==5.9.7
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycodestyle==2.11.1
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pygments==2.17.2
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - rdkit-pypi==2022.9.5
      - requests==2.31.0
      - ruamel-yaml==0.18.5
      - ruamel-yaml-clib==0.2.8
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - six==1.16.0
      - snowballstemmer==2.2.0
      - sphinx==7.2.6
      - sphinxcontrib-applehelp==1.0.7
      - sphinxcontrib-devhelp==1.0.5
      - sphinxcontrib-htmlhelp==2.0.4
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.6
      - sphinxcontrib-serializinghtml==1.1.9
      - stack-data==0.6.3
      - submitit==1.5.1
      - tabulate==0.9.0
      - threadpoolctl==3.2.0
      - tqdm==4.66.1
      - traitlets==5.14.2
      - typer==0.9.0
      - tzdata==2023.4
      - urllib3==2.1.0
      - wcwidth==0.2.13
prefix: /home/grads/a/anath/anaconda3/envs/gflow
